version: '3.8'

services:
  backend:
    build:
      context: ./backend  # This tells Docker to look in the `backend/` directory for the Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"  # Expose Django backend on port 8000
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///db.sqlite3  # SQLite database